spring:
  application:
    name: cannal-sync-redis
  datasource:
    #使用springboot2.0后内置的HikariCP
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.87.67.162:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: yakai
    password: Yakai2018@
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #Redis配置
  redis:
    host: 58.87.67.162
    port: 7000
    password: Yakai2018@
    database: 0
    jedis:
      pool:
        #最大连接数（负值表示没有限制）
        max-active: 100
        #最大空闲链接
        max-idle: 10
        #最小空闲链接
        min-idle: 5
        #最大阻塞时间 负值表示不限制
        max-wait: -1ms



mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: cn.zhengyk.sync.model

# canal相关配置
canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  username:
  password:
  subscribe: test.blog
# subscribe 概述
# 1）  所有：.*   or  .*\\..*
# 2）  "test"库下所有表： test\\..*
# 3）  "test"下的以"sys"打头的表：test\\.sys.*
# 4）  "test"下的具体一张表：test.blog   blog表
# 5）  多个规则组合使用：test\\..*,test.sys_user,test.sys_role (逗号分隔)

